%module Library

%include "lib/Cache.i"
%include "lib/common.i"
%include "lib/File.i"
%include "lib/io.i"
%include "lib/lapack.i"
%include "lib/List.i"
%include "lib/Mathematics.i"
%include "lib/Parallel.i"
%include "lib/Signal.i"
%include "lib/SimpleFile.i"
%include "lib/Time.i"
%include "lib/Trie.i"
%include "lib/Version.i"
