# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
# added all tags, I don't know how to just add everything
# because the bot compares tag names rather than regex :(
exemptLabels:
  - "good first issue"
  - "Tag: ARM64"
  - "Tag: Cleanup"
  - "Tag: cmake"
  - "Tag: Development Task"
  - "Tag: Discussion"
  - "Tag: Documentation"
  - "Tag: Gaussian Process"
  - "Tag: GSoC"
  - "Tag: Hackathon"
  - "Tag: Infrastructure"
  - "Tag: Installation"
  - "Tag: Memory Problems"
  - "Tag: Meta Examples"
  - "Tag: Performance Improvement"
  - "Tag: Publicity"
  - "Tag: SWIG"
  - "Tag: Testing"
  - "Tag: UX"
  - "Tag: Website"
  - "Type: Bug"
  - "Type: Bugfixing"
  - "ML: Deep Learning"
  - "ML: Kernel Methods"
  - "ML: New Algorithms"
  - "ML: Numerical Optimization"

# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue is now being closed due to a lack of activity. Feel free to reopen it.
