dyn.load("shogun-Linux-x86_64.debug")
traindat <- array(c(1,2,2,1,4,8,5,7),dim=c(4,2))
trainlab <- array(c(1,1,-1,-1),dim=c(1,4))
.External("sg","set_features", "TRAIN", traindat)
feat <- .External("sg","get_features", "TRAIN") 
.External("sg","set_labels", "TRAIN", trainlab) 
lab <- .External("sg","get_labels", "TRAIN") 
.External("sg","send_command", "loglevel ALL")
.External("sg","send_command","clean_kernels")
.External("sg","send_command", "use_linadd 1" )
.External("sg","send_command", "set_kernel GAUSSIAN REAL 50 10")
.External("sg","send_command", "init_kernel TRAIN")
kt <- .External("sg","get_kernel_matrix")
.External("sg","send_command", "new_svm LIGHT")
.External("sg","send_command", "c 10.0")
.External("sg","send_command", "svm_epsilon 0.1")
.External("sg","send_command", "svm_train")
svmAsList <- .External("sg","get_svm")
.External("sg","set_features", "TEST", testdat)
.External("sg","set_labels", "TEST", testlab)
.External("sg","send_command", "init_kernel TEST")
kte <- .External("sg","get_kernel_matrix")
out <- .External("sg","svm_classify") 

#valerr=mean(testlab~=sign(out)) ]

