#ifndef __INTERFACEDATATYPE__H_
#define __INTERFACEDATATYPE__H_

#if !defined(HAVE_SWIG)

enum SGInterfaceDataType {
	SGIDT_UNKNOWN,
	SGIDT_BYTE,
	SGIDT_CHAR,
	SGIDT_DREAL,
	SGIDT_INT,
	SGIDT_SHORT,
	SGIDT_SHORTREAL,
	SGIDT_WORD,
	SGIDT_SPARSEBYTE,
	SGIDT_SPARSECHAR,
	SGIDT_SPARSEDREAL,
	SGIDT_SPARSEINT,
	SGIDT_SPARSESHORT,
	SGIDT_SPARSESHORTREAL,
	SGIDT_SPARSEWORD,
};

#endif // !HAVE_SWIG
#endif // __INTERFACEDATATYPE__H_
