# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r test_swig.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_std__shared_ptrT_test__Base_t', contains = 'C++Reference')
setClass('_p_std__shared_ptrT_test__Base_const_t', contains = 'C++Reference')
setClass('_p_std__shared_ptrT_test__Machine_t', contains = 'C++Reference')
setClass('_p_std__shared_ptrT_test__Machine_const_t', contains = 'C++Reference')
setClass('_p_test__Base', contains = 'C++Reference')
setClass('_p_std__shared_ptrT_test__Base_t', contains = c('_p_test__Base'))
setClass('_p_test__Machine', contains = c('_p_test__Base'))
setClass('_p_std__shared_ptrT_test__Machine_t', contains = c('_p_test__Machine', '_p_std__shared_ptrT_test__Base_t'))



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of delete_Base

`delete_Base` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_Base', self, PACKAGE='test');
  
}

attr(`delete_Base`, 'returnType') = 'void'
attr(`delete_Base`, "inputTypes") = c('_p_test__Base')
class(`delete_Base`) = c("SWIGFunction", class('delete_Base'))

# Start of Base_equals

`Base_equals` = function(self, v, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  if (inherits(v, "ExternalReference")) v = slot(v,"ref") 
  ;.Call('R_swig_Base_equals', self, v, as.logical(.copy), PACKAGE='test');
  
}

attr(`Base_equals`, 'returnType') = 'logical'
attr(`Base_equals`, "inputTypes") = c('_p_test__Base', '_p_test__Base')
class(`Base_equals`) = c("SWIGFunction", class('Base_equals'))

# Start of Base_name

`Base_name` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_Base_name', self, as.logical(.copy), PACKAGE='test');
  
}

attr(`Base_name`, 'returnType') = 'character'
attr(`Base_name`, "inputTypes") = c('_p_test__Base')
class(`Base_name`) = c("SWIGFunction", class('Base_name'))

# Start of Base_set

`Base_set__SWIG_2` = function(self, s, v)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s = as(s, "character"); 
  v = as.integer(v);
  
  if(length(v) > 1) {
    warning("using only the first element of v");
  };
  
  ;.Call('R_swig_Base_set__SWIG_2', self, s, v, PACKAGE='test');
  
}

attr(`Base_set__SWIG_2`, 'returnType') = 'void'
attr(`Base_set__SWIG_2`, "inputTypes") = c('_p_test__Base', 'character', 'integer')
class(`Base_set__SWIG_2`) = c("SWIGFunction", class('Base_set__SWIG_2'))

# Start of Base_set

`Base_set__SWIG_3` = function(self, s, v)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s = as(s, "character"); 
  if (inherits(v, "ExternalReference")) v = slot(v,"ref") 
  ;.Call('R_swig_Base_set__SWIG_3', self, s, v, PACKAGE='test');
  
}

attr(`Base_set__SWIG_3`, 'returnType') = 'void'
attr(`Base_set__SWIG_3`, "inputTypes") = c('_p_test__Base', 'character', '_p_std__shared_ptrT_test__Base_t')
class(`Base_set__SWIG_3`) = c("SWIGFunction", class('Base_set__SWIG_3'))

`Base_set` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
# dispatch functions 2
  if (argc == 3) {
    if ((extends(argtypes[1], '_p_test__Base') || is.null(argv[[1]])) && is.character(argv[[2]]) && length(argv[[2]]) == 1 && extends(argtypes[3], '_p_std__shared_ptrT_test__Base_t') && length(argv[[3]]) == 1) {
      f <- Base_set__SWIG_3; 
    }
    else if ((extends(argtypes[1], '_p_test__Base') || is.null(argv[[1]])) && is.character(argv[[2]]) && length(argv[[2]]) == 1 && ( (is.integer(argv[[3]]) || is.numeric(argv[[3]])) && length(argv[[3]]) == 1 )) {
      f <- Base_set__SWIG_2; 
    }
  } else {
    stop("cannot find overloaded function for Base_set with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of accessor method for test::Base
setMethod('$', '_p_test__Base', function(x, name)

{
  accessorFuns = list('equals' = Base_equals, 'name' = Base_name);
  ;        idx = match(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for test::Base
# Start of accessor method for test::Base
setMethod('$<-', '_p_test__Base', function(x, name, value)

{
  accessorFuns = list('set' = Base_set);
  ;        idx = match(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_test__Base', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('set' = Base_set);
  ;        idx = match(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for test::Base
setMethod('delete', '_p_test__Base', function(obj) {delete_test__Base(obj)})
# Start of new_Machine

`Machine` = function()
{
  ;ans = .Call('R_swig_new_Machine', PACKAGE='test');
  ans <- if (is.null(ans)) ans
  else new("_p_std__shared_ptrT_test__Machine_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_Machine)
  ans
  
}

attr(`Machine`, 'returnType') = '_p_test__Machine'
class(`Machine`) = c("SWIGFunction", class('Machine'))

# Start of delete_Machine

`delete_Machine` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_Machine', self, PACKAGE='test');
  
}

attr(`delete_Machine`, 'returnType') = 'void'
attr(`delete_Machine`, "inputTypes") = c('_p_test__Machine')
class(`delete_Machine`) = c("SWIGFunction", class('delete_Machine'))

# Start of Machine_name

`Machine_name` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_Machine_name', self, as.logical(.copy), PACKAGE='test');
  
}

attr(`Machine_name`, 'returnType') = 'character'
attr(`Machine_name`, "inputTypes") = c('_p_test__Machine')
class(`Machine_name`) = c("SWIGFunction", class('Machine_name'))

# Start of Machine_own

`Machine_own` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_Machine_own', self, as.logical(.copy), PACKAGE='test');
  
}

attr(`Machine_own`, 'returnType') = 'character'
attr(`Machine_own`, "inputTypes") = c('_p_test__Machine')
class(`Machine_own`) = c("SWIGFunction", class('Machine_own'))

# Start of accessor method for test::Machine
setMethod('$', '_p_test__Machine', function(x, name)

{
  accessorFuns = list('name' = Machine_name, 'own' = Machine_own);
  ;        idx = match(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for test::Machine
setMethod('delete', '_p_test__Machine', function(obj) {delete_test__Machine(obj)})


