# format: name: featuretype, accuracy, [parameters]
{
	'AUC':['Word', 1e-8, ['subkernel']],
	'Byte':['Byte', 1e-8, []],
	'CanberraWord':['Word', 1e-13, ['width_']],
	'Char':['Char', 1e-8, []],
	'Chi2':['Real', 1e-8, ['size_', 'width_']],
	'Combined':['Combined', 1e-8, ['append_subkernel_weights']],
	'Const':['Real', 1e-0, ['c']],
	'Custom':['Real', 1e-8, []],
	'CommWordString':['Wordstring', 1e-9, ['use_sign', 'normalization']],
	'CommUlongString':['String', 1e-9, ['use_sign', 'normalization']],
	'Diag':['Real', 1e-0, ['diag']],
	'Distance':['Real', 1e-8, ['distance']],
	'FixedDegreeString':['String', 1e-10, ['degree']],
	'Gaussian':['Real', 1e-8, ['width_']],
	'GaussianShift':['Real', 1e-8, ['width_', 'max_shift', 'shift_step']],
	'HammingWord':['Word', 1e-14, ['width_', 'use_sign']],
	'HistogramWord':['Word', 1e-6, ['plugin_estimate']],
	'Int':['Int', 1e-8, []],
	'Linear':['Real', 1e-8, ['scale']],
	'LinearByte':['Byte', 1e-8, ['do_rescale', 'scale']],
	'LinearString':['String', 1e-8, ['scale']],
	'LinearWord':['Word', 1e-8, ['do_rescale', 'scale']],
	'LocalAlignmentString':['String', 1e-8, []],
	'LocalityImprovedString':['String', 1e-8,
		['length', 'inner_degree', 'outer_degree']],
	'ManhattenWord':['Word', 1e-14, ['width_']],
	'MindyGram':['mindy', 1e-8, ['measure', 'width_']],
	'Poly':['Real', 1e-6, ['degree', 'inhomogene', 'use_normalization']],
	'PolyMatchString':['String', 1e-10, ['degree', 'inhomogene']],
	'PolyMatchWord':['Word', 1e-11, ['degree', 'inhomogene']],
	'Real':['Real', 1e-8, []],
	'SalzbergWord':['Word', 1e-6, ['plugin_estimate']],
	'Short':['Short', 1e-8, []],
	'Sigmoid':['Real', 1e-9, ['size_', 'gamma_', 'coef0']],
	'SimpleLocalityImprovedString':['String', 1e-15,
		['length', 'inner_degree', 'outer_degree']],
	'SparseReal':['Real', 1e-8, []],
	'SparseGaussian':['Real', 1e-8, ['width_']],
	'SparseLinear':['Real', 1e-8, ['scale']],
	'SparsePoly':['Real', 1e-8, ['size_', 'degree', 'inhomogene', 'use_normalization']],
	'SparseWord':['Word', 1e-8, []],
	'StringCharKernel':['String', 1e-8, []],
	'StringIntKernel':['String', 1e-8, []],
	'StringRealKernel':['String', 1e-8, []],
	'StringUlongKernel':['String', 1e-8, []],
	'StringWordKernel':['String', 1e-8, []],
	'Ulong':['Ulong', 1e-8, []],
	'WeightedDegreePositionString':['String', 1e-8,
		['degree', 'weights', 'shift', 'shift_len', 'max_mismatch',
		'use_normalization', 'mkl_stepsize']],
	'WeightedDegreeString':['String', 1e-10,
		['degree', 'max_mismatch', 'use_normalization',
		'block_computation', 'mkl_stepsize', 'which_degree', 'weights']],
	'WeightedCommWordString':['Wordstring', 1e-9, ['use_sign', 'normalization']],
	'Word':['Word', 1e-8, []],
	'WordMatch':['Word', 1e-8, ['degree', 'do_rescale', 'scale']],
}
