# format: name: featuretype, accuracy, [parameters]
{
	'Chi2':['real', 1e-8, ['size_']],
	'CommWordString':['word', 1e-9, ['use_sign', 'normalization']],
	'FixedDegreeString':['string', 1e-10, ['degree']],
	'Gaussian':['real', 1e-8, ['width_']],
	'HammingWord':['word', 1e-8, ['width_', 'use_sign']],
	'Linear':['real', 1e-8, ['scale']],
	'LocalAlignmentString':['string', 1e-8, []],
	'Poly':['real', 1e-6, ['degree', 'inhomogene', 'use_normalization']],
	'LinearString':['string', 1e-8, ['scale']],
	'LinearWord':['word', 1e-8, ['do_rescale', 'scale']],
	'LocalityImprovedString':['string', 1e-8,
		['length', 'inner_degree', 'outer_degree']],
	'ManhattanWord':['word', 1e-8, ['width_']],
	'Sigmoid':['real', 1e-9, ['size_', 'gamma_', 'coef0']],
	'SimpleLocalityImprovedString':['string', 1e-15,
		['length', 'inner_degree', 'outer_degree']],
	'PolyMatchString':['string', 1e-10,
		['degree', 'inhomogene', 'use_normalization']],
	'WeightedDegreePositionString':['string', 1e-8,
		['degree', 'shift', 'use_normalization', 'max_mismatch',
		'mkl_stepsize']],
	'WeightedDegreeString':['string', 1e-10,
		['degree', 'max_mismatch', 'use_normalization',
		'block_computation', 'mkl_stepsize', 'which_degree', 'weights']],
	'WeightedCommWordString':['word', 1e-9, ['use_sign', 'normalization']],
}
