%{
#include <shogun/lib/Compressor.h>
#include <shogun/features/FeatureTypes.h>
#include <shogun/features/Features.h>
#include <shogun/features/StreamingFeatures.h>
#include <shogun/features/StringFeatures.h>
#include <shogun/features/StreamingStringFeatures.h>
#include <shogun/features/StringFileFeatures.h>
#include <shogun/features/DotFeatures.h>
#include <shogun/features/BinnedDotFeatures.h>
#include <shogun/features/StreamingDotFeatures.h>
#include <shogun/features/SparseFeatures.h>
#include <shogun/features/StreamingSparseFeatures.h>
#include <shogun/features/SimpleFeatures.h>
#include <shogun/features/StreamingSimpleFeatures.h>
#include <shogun/features/DummyFeatures.h>
#include <shogun/features/AttributeFeatures.h>
#include <shogun/features/Alphabet.h>
#include <shogun/features/CombinedFeatures.h>
#include <shogun/features/CombinedDotFeatures.h>
#include <shogun/features/Labels.h>
#include <shogun/features/RealFileFeatures.h>
#include <shogun/features/FKFeatures.h>
#include <shogun/features/TOPFeatures.h>
#include <shogun/features/SNPFeatures.h>
#include <shogun/features/WDFeatures.h>
#include <shogun/features/HashedWDFeatures.h>
#include <shogun/features/HashedWDFeaturesTransposed.h>
#include <shogun/features/PolyFeatures.h>
#include <shogun/features/SparsePolyFeatures.h>
#include <shogun/features/LBPPyrDotFeatures.h>
#include <shogun/features/ExplicitSpecFeatures.h>
#include <shogun/features/ImplicitWeightedSpecFeatures.h>
%}
