%{
#include <shogun/lib/Compressor.h>
#include <shogun/features/FeatureTypes.h>
#include <shogun/features/Features.h>
#include <shogun/features/streaming/StreamingFeatures.h>
#include <shogun/features/StringFeatures.h>
#include <shogun/features/streaming/StreamingStringFeatures.h>
#include <shogun/features/StringFileFeatures.h>
#include <shogun/features/DotFeatures.h>
#include <shogun/features/DirectorDotFeatures.h>
#include <shogun/features/BinnedDotFeatures.h>
#include <shogun/features/streaming/StreamingDotFeatures.h>
#include <shogun/features/SparseFeatures.h>
#include <shogun/features/streaming/StreamingSparseFeatures.h>
#include <shogun/features/DenseFeatures.h>
#include <shogun/features/streaming/StreamingDenseFeatures.h>
#include <shogun/features/DenseSubsetFeatures.h>
#include <shogun/features/DummyFeatures.h>
#include <shogun/features/AttributeFeatures.h>
#include <shogun/features/Alphabet.h>
#include <shogun/features/CombinedFeatures.h>
#include <shogun/features/CombinedDotFeatures.h>
#include <shogun/features/HashedDocDotFeatures.h>
#include <shogun/features/RandomKitchenSinksDotFeatures.h>
#include <shogun/features/RandomFourierDotFeatures.h>
#include <shogun/labels/Labels.h>
#include <shogun/labels/LabelsFactory.h>
#include <shogun/labels/DenseLabels.h>
#include <shogun/labels/BinaryLabels.h>
#include <shogun/labels/LatentLabels.h>
#include <shogun/labels/MulticlassLabels.h>
#include <shogun/labels/RegressionLabels.h>
#include <shogun/labels/StructuredLabels.h>
#include <shogun/labels/MulticlassMultipleOutputLabels.h>
#include <shogun/features/RealFileFeatures.h>
#include <shogun/features/RealFileFeatures.h>
#include <shogun/features/FKFeatures.h>
#include <shogun/features/TOPFeatures.h>
#include <shogun/features/SNPFeatures.h>
#include <shogun/features/WDFeatures.h>
#include <shogun/features/HashedWDFeatures.h>
#include <shogun/features/HashedWDFeaturesTransposed.h>
#include <shogun/features/PolyFeatures.h>
#include <shogun/features/SparsePolyFeatures.h>
#include <shogun/features/LBPPyrDotFeatures.h>
#include <shogun/features/ExplicitSpecFeatures.h>
#include <shogun/features/ImplicitWeightedSpecFeatures.h>
#include <shogun/features/DataGenerator.h>
#include <shogun/features/streaming/generators/MeanShiftDataGenerator.h>
#include <shogun/features/streaming/generators/GaussianBlobsDataGenerator.h>
#include <shogun/features/LatentFeatures.h>
#include <shogun/features/MatrixFeatures.h>
%}
