%{
#include <features/FeatureTypes.h>
#include <kernel/Kernel.h>
#include <kernel/normalizer/KernelNormalizer.h>
#include <kernel/PyramidChi2.h>
#include <kernel/ANOVAKernel.h>
#include <kernel/AUCKernel.h>
#include <kernel/normalizer/AvgDiagKernelNormalizer.h>
#include <kernel/normalizer/RidgeKernelNormalizer.h>
#include <kernel/CauchyKernel.h>
#include <kernel/Chi2Kernel.h>
#include <kernel/CombinedKernel.h>
#include <kernel/ProductKernel.h>
#include <kernel/string/CommUlongStringKernel.h>
#include <kernel/string/CommWordStringKernel.h>
#include <kernel/CircularKernel.h>
#include <kernel/ConstKernel.h>
#include <kernel/CustomKernel.h>
#include <kernel/DiagKernel.h>
#include <kernel/string/DistantSegmentsKernel.h>
#include <kernel/normalizer/DiceKernelNormalizer.h>
#include <kernel/ExponentialKernel.h>
#include <kernel/normalizer/ScatterKernelNormalizer.h>
#include <kernel/normalizer/VarianceKernelNormalizer.h>
#include <kernel/DistanceKernel.h>
#include <kernel/string/FixedDegreeStringKernel.h>
#include <kernel/GaussianKernel.h>
#include <kernel/DirectorKernel.h>
#include <kernel/GaussianShiftKernel.h>
#include <kernel/GaussianShortRealKernel.h>
#include <kernel/HistogramIntersectionKernel.h>
#include <kernel/string/HistogramWordStringKernel.h>
#include <kernel/normalizer/IdentityKernelNormalizer.h>
#include <kernel/InverseMultiQuadricKernel.h>
#include <kernel/DotKernel.h>
#include <kernel/LinearKernel.h>
#include <kernel/string/LinearStringKernel.h>
#include <kernel/string/SparseSpatialSampleStringKernel.h>
#include <kernel/string/LocalAlignmentStringKernel.h>
#include <kernel/string/LocalityImprovedStringKernel.h>
#include <kernel/string/MatchWordStringKernel.h>
#include <kernel/MultiquadricKernel.h>
#include <kernel/string/OligoStringKernel.h>
#include <kernel/PolyKernel.h>
#include <kernel/string/PolyMatchStringKernel.h>
#include <kernel/PowerKernel.h>
#include <kernel/LogKernel.h>
#include <kernel/string/GaussianMatchStringKernel.h>
#include <kernel/string/SNPStringKernel.h>
#include <kernel/string/RegulatoryModulesStringKernel.h>
#include <kernel/string/PolyMatchWordStringKernel.h>
#include <kernel/string/SalzbergWordStringKernel.h>
#include <kernel/SigmoidKernel.h>
#include <kernel/string/SimpleLocalityImprovedStringKernel.h>
#include <kernel/SparseKernel.h>
#include <kernel/SphericalKernel.h>
#include <kernel/SplineKernel.h>
#include <kernel/normalizer/SqrtDiagKernelNormalizer.h>
#include <kernel/string/StringKernel.h>
#include <kernel/normalizer/TanimotoKernelNormalizer.h>
#include <kernel/TensorProductPairKernel.h>
#include <kernel/TStudentKernel.h>
#include <kernel/WaveletKernel.h>
#include <kernel/WaveKernel.h>
#include <kernel/string/WeightedCommWordStringKernel.h>
#include <kernel/string/WeightedDegreePositionStringKernel.h>
#include <kernel/string/WeightedDegreeStringKernel.h>
#include <kernel/WeightedDegreeRBFKernel.h>
#include <kernel/string/SpectrumMismatchRBFKernel.h>
#include <kernel/normalizer/ZeroMeanCenterKernelNormalizer.h>
#include <kernel/RationalQuadraticKernel.h>
#include <kernel/CircularKernel.h>
#include <kernel/JensenShannonKernel.h>
#include <kernel/LinearARDKernel.h>
#include <kernel/GaussianARDKernel.h>
%}
