execute_process(COMMAND ${EXECUTABLE} ${FILE} ${ARGS} RESULT_VARIABLE RESULT)
string(TOUPPER "${RESULT}" RESULT)
if (RESULT MATCHES ".*THE FOLLOWING TESTS FAILED.*")
	#if (GDB_COMMAND AND GDB_SCRIPT)
	#	execute_process(COMMAND ${GDB_COMMAND}
	#		--command=${GDB_SCRIPT}
	#		--args ${EXECUTABLE} ${FILE} ${ARGS}
	#			RESULT_VARIABLE GDB_RESULT)
	#endif()
	MESSAGE( FATAL_ERROR "FAIL:  ${ARGS}" )
endif()
