EXECUTE_PROCESS(
	     COMMAND ${CMAKE_COMMAND} -E chdir ${SRC_DIR} ${SVN_EXEC} info
	     OUTPUT_VARIABLE SVN_INFO_OUTPUT
	     RESULT_VARIABLE SVN_INFO_RETURN
	     ERROR_VARIABLE SVN_INFO_ERROR
	     OUTPUT_STRIP_TRAILING_WHITESPACE
	)

IF (NOT ${SVN_INFO_RETURN})
	STRING(REGEX MATCH "Revision: [0-9]+" CHECKED_OUT_REVISION ${SVN_INFO_OUTPUT})
	STRING(REGEX REPLACE "Revision: ([0-9]+)" "\\1" CHECKED_OUT_REVISION ${CHECKED_OUT_REVISION})

	IF (${CHECKED_OUT_REVISION} VERSION_EQUAL ${REVISION})
		EXECUTE_PROCESS(
		     COMMAND ${CMAKE_COMMAND} -E touch ${STAMP_DIR}/${PROJECT_NAME}-download
		)
	ENDIF()
ENDIF()